application: emarer
version: 1
api_version: 1
runtime: python

default_expiration: "4d 5h"

handlers:
- url: /stylesheets
  static_dir: assets/stylesheets
- url: /javascripts
  static_dir: assets/javascripts
- url: /images
  static_dir: assets/images
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: .*
  script: main.py
