application: emarer
version: 1
runtime: python
api_version: 1

handlers:
- url: /resources
  static_dir: public/resources

- url: /javascripts
  static_dir: public/javascripts
  
- url: /stylesheets
  static_dir: public/stylesheets  
  
- url: .*
  script: main.py
